namespace SupermarketBilling.Application.Contracts;

/// <param name="Quantity">In the pack unit given by <paramref name="VariantUnitId"/>. For counts: the counted quantity.</param>
/// <param name="Direction">Adjustments only: IN or OUT.</param>
/// <param name="UnitCost">Cost per pack, for stock coming in (opening, adjustment in). Defaults to the current average.</param>
/// <param name="BatchNumber">Incoming stock of batch-tracked products: the batch (created if new).</param>
/// <param name="BatchId">Outgoing stock: take from this batch only.</param>
public sealed record StockLineRequest(
    Guid VariantId,
    Guid VariantUnitId,
    decimal Quantity,
    string? Direction = null,
    decimal? UnitCost = null,
    string? BatchNumber = null,
    DateOnly? ExpiresOn = null,
    DateOnly? ManufacturedOn = null,
    Guid? BatchId = null);

/// <param name="IdempotencyKey">Generated by the client once per document; retries with the same key return the same document.</param>
/// <param name="NegativeStockOverride">Confirms going below zero where the rule allows an authorised override.</param>
public sealed record PostStockDocumentRequest(
    string Type,
    Guid StoreId,
    Guid? TargetStoreId,
    string Reason,
    string? Note,
    string IdempotencyKey,
    bool NegativeStockOverride,
    IReadOnlyList<StockLineRequest> Lines);

public sealed record StockMovementDto(
    long Sequence, Guid StoreId, Guid VariantId, string VariantName, string? BatchNumber, string MovementType,
    decimal Quantity, decimal UnitCost, decimal Value, decimal BalanceAfter);

public sealed record StockDocumentDto(
    Guid Id, string Type, string Number, Guid StoreId, Guid? TargetStoreId, DateOnly BusinessDate, string Reason, string? Note,
    bool NegativeStockOverride, string PostedBy, DateTimeOffset PostedAtUtc, IReadOnlyList<StockMovementDto> Movements);

public sealed record StockDocumentSummaryDto(
    Guid Id, string Type, string Number, Guid StoreId, Guid? TargetStoreId, DateOnly BusinessDate, string Reason, string PostedBy, DateTimeOffset PostedAtUtc);

public sealed record StockOnHandDto(
    Guid VariantId, string VariantCode, string VariantName, string UnitCode, decimal Quantity, decimal AverageCost, decimal Value,
    decimal? MinimumQuantity, decimal? ReorderQuantity, bool IsLow, bool IsNegative);

public sealed record LedgerEntryDto(
    long Sequence, DateTimeOffset OccurredAtUtc, DateOnly BusinessDate, string MovementType, decimal Quantity, decimal UnitCost,
    decimal Value, decimal BalanceAfter, string? BatchNumber, string DocumentType, Guid DocumentId, string? DocumentNumber, string PostedBy);

public sealed record BatchStockDto(
    Guid BatchId, Guid VariantId, string VariantName, string BatchNumber, DateOnly? ExpiresOn, int? DaysToExpiry, bool IsExpired, decimal Quantity);

public sealed record StockAgeingDto(Guid VariantId, string VariantName, decimal Days0To30, decimal Days31To60, decimal Days61To90, decimal Over90, decimal Value);

public sealed record StockValuationDto(Guid StoreId, string StoreName, string ValuationMethod, int Items, int NegativeItems, decimal TotalValue);

public sealed record InventorySettingsDto(string ValuationMethod, bool ValuationLocked);

public sealed record UpdateInventorySettingsRequest(string ValuationMethod);

public sealed record NegativeStockRuleDto(
    Guid Id, Guid? StoreId, Guid? ProductId, string Mode, decimal? LimitQuantity, string Reason, string CreatedBy,
    DateTimeOffset CreatedAtUtc, bool IsActive, Guid? ApprovalRequestId, DateTimeOffset? SupersededAtUtc);

public sealed record SetNegativeStockRuleRequest(Guid? StoreId, Guid? ProductId, string Mode, decimal? LimitQuantity, string Reason);

public sealed record SetNegativeStockRuleResponse(string Outcome, Guid RuleId, Guid? ApprovalRequestId, string Message);

public sealed record SetReorderLevelRequest(Guid StoreId, Guid VariantId, decimal MinimumQuantity, decimal ReorderQuantity);
