namespace SupermarketBilling.Infrastructure.Security;

/// <summary>Bound from the "Security" configuration section (environment: Security__*).</summary>
public sealed class SecurityOptions
{
    public const string SectionName = "Security";

    /// <summary>Base64 256-bit key encrypting secrets at rest (MFA secrets). Generated by setup-dev.ps1.</summary>
    public string DataProtectionKey { get; set; } = string.Empty;

    /// <summary>Send cookies with the Secure flag. Must be true whenever the site is served over HTTPS.</summary>
    public bool SecureCookies { get; set; } = true;

    public int SessionIdleMinutes { get; set; } = 30;

    public int SessionAbsoluteHours { get; set; } = 12;

    public int MaxFailedLogins { get; set; } = 5;

    public int LockoutMinutes { get; set; } = 15;

    public int PasswordResetMinutes { get; set; } = 30;

    public int ApprovalLifetimeDays { get; set; } = 7;

    /// <summary>PBKDF2-HMAC-SHA512 iterations (OWASP 2023+ guidance: 210,000).</summary>
    public int PasswordHashIterations { get; set; } = 210_000;

    /// <summary>Businesses this installation is licensed for.</summary>
    public int MaxBusinesses { get; set; } = 1;

    /// <summary>File holding the one-time initial setup code (created only while no users exist).</summary>
    public string SetupCodeFile { get; set; } = Path.Combine("App_Data", "setup-code.txt");
}
