<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sb-backup</AssemblyName>
    <RootNamespace>SupermarketBilling.BackupTool</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SupermarketBilling.UnitTests" />
    <InternalsVisibleTo Include="SupermarketBilling.IntegrationTests" />
  </ItemGroup>

</Project>
