<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SupermarketBilling.Domain\SupermarketBilling.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\SupermarketBilling.Application\SupermarketBilling.Application.csproj" />
    <ProjectReference Include="..\..\..\src\SupermarketBilling.Infrastructure\SupermarketBilling.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\SupermarketBilling.Api\SupermarketBilling.Api.csproj" />
    <ProjectReference Include="..\..\..\src\SupermarketBilling.BackupTool\SupermarketBilling.BackupTool.csproj" />
  </ItemGroup>

</Project>